[package]
name = "goxoy-file-chunker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3="0.1"
serde_json = "1.0.103"
serde = { version = "1.0", features = ["derive"] }
